# Generated by Django 2.2.4 on 2019-08-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0002_auto_20190827_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='tag',
        ),
        migrations.AddField(
            model_name='test',
            name='tag_set',
            field=models.ManyToManyField(blank=True, related_name='test_set', through='topology.Mapping', to='topology.Tag', verbose_name='theme_set'),
        ),
    ]
