# Generated by Django 2.2.4 on 2019-08-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0003_auto_20190827_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ('label',), 'verbose_name': 'theme', 'verbose_name_plural': 'themes'},
        ),
    ]
