# Generated by Django 2.2.4 on 2019-08-27 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0004_auto_20190827_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='test',
            name='grade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)], verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='test',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP v4 ou 6'),
        ),
        migrations.AlterField(
            model_name='test',
            name='ipv4',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP v4 as is'),
        ),
        migrations.AlterField(
            model_name='test',
            name='ipv6',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6', verbose_name='IP v6'),
        ),
        migrations.AlterField(
            model_name='test',
            name='ipv6_forced',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP v6 (ipv4 will be converted)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='percent'),
        ),
        migrations.AlterField(
            model_name='test',
            name='progress',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progress'),
        ),
        migrations.AlterField(
            model_name='test',
            name='random_date',
            field=models.DateField(blank=True, null=True, verbose_name='random date'),
        ),
        migrations.AlterField(
            model_name='test',
            name='random_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='random datetime'),
        ),
        migrations.AlterField(
            model_name='test',
            name='random_time',
            field=models.TimeField(blank=True, null=True, verbose_name='random time'),
        ),
        migrations.AlterField(
            model_name='test',
            name='raw_data',
            field=models.BinaryField(blank=True, editable=True, max_length=127, null=True, verbose_name='raw data'),
        ),
    ]
